### ISSUE TITLE
AttributeError: module 'util' has no attribute 'MaxScaler'

### ISSUE THREAD

**Issue by tomisalready** [jingw2/demand_forecast#8]
Traceback (most recent call last):
  File "tpa_lstm.py", line 249, in <module>
    losses, mape_list = train(X, y, args)
  File "tpa_lstm.py", line 134, in train
    yscaler = util.MaxScaler()
AttributeError: module 'util' has no attribute 'MaxScaler'

**Comment by tomisalready** [comment]
thank you so much !!!
